apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}

vpc:
  id: "${VPC_ID}"
  subnets:
    private:
      ${AWS_REGION}a: 
        id: "${PRIVATE_SUBNET_1}"
      ${AWS_REGION}c:
        id: "${PRIVATE_SUBNET_2}"

nodeGroups:
  - name: ${NODE_GROUP_NAME}
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    amiFamily: AmazonLinux2
    volumeSize: 20

