apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-reporter
  template:
    metadata:
      labels:
        app: youtube-reporter
    spec:
      containers:
        - name: youtube-reporter
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
