apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-reporter
  template:
    metadata:
      labels:
        app: youtube-reporter
    spec:
      containers:
        - name: youtube-reporter
<<<<<<< HEAD
          image: 492021314651.dkr.ecr.us-west-2.amazonaws.com/youtube-reporter-app:build-23
=======
          image: 492021314651.dkr.ecr.us-west-2.amazonaws.com/youtube-reporter-app:build-19
>>>>>>> 790a4b416ce6bce289f9eff004c52b71c6b1e344
          ports:
            - containerPort: 8000
