apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth/?(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /report/?(.*)
        pathType: Prefix
        backend:
          service:
            name: report-service
            port:
              number: 80
      - path: /document/?(.*)
        pathType: Prefix
        backend:
          service:
            name: document-service
            port:
              number: 80
      - path: /youtube/?(.*)
        pathType: Prefix
        backend:
          service:
            name: youtube-service
            port:
              number: 80
      - path: /analyzer/?(.*)
        pathType: Prefix
        backend:
          service:
            name: analyzer-service
            port:
              number: 80
