services:
  - name: auth-service
    image: 922805825674.dkr.ecr.us-east-1.amazonaws.com/auth_service:latest
    port: 8000
    ingressHost: auth.example.com

  - name: report-service
    image: 922805825674.dkr.ecr.us-east-1.amazonaws.com/report_service:latest
    port: 8000
    ingressHost: report.example.com

  - name: document-service
    image: 922805825674.dkr.ecr.us-east-1.amazonaws.com/document_service:latest
    port: 8000
    ingressHost: document.example.com

  - name: youtube-service
    image: 922805825674.dkr.ecr.us-east-1.amazonaws.com/youtube_service:latest
    port: 8000
    ingressHost: youtube.example.com

  - name: analyzer-service
    image: 922805825674.dkr.ecr.us-east-1.amazonaws.com/analyzer_service:latest
    port: 8000
    ingressHost: analyzer.example.com

serviceAccount:
  create: false
  name: ""
