# ArgoCD 기본 설정 덮어쓰기
configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    exec.enabled: true
    timeout.reconciliation: 30s

server:
  service:
    type: ClusterIP 
  ingress:
    enabled: true
    ingressClassName: alb
    hosts:
      - argocd.internal.example.com     # 나중에 Ingress 쓸 거면 true로 변경

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true
