# ArgoCD 기본 설정 덮어쓰기
configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    exec.enabled: true
    timeout.reconciliation: 30s

server:
  service:
    type: LoadBalancer  # 외부에서 접속 가능하게 하려면 LoadBalancer
  ingress:
    enabled: false      # 나중에 Ingress 쓸 거면 true로 변경

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true
