# ArgoCD 기본 설정 덮어쓰기
configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    exec.enabled: true
    timeout.reconciliation: 30s
    # ALB URL 설정
    url: "${ARGOCD_URL}"
  params:
    # ArgoCD 서버를 insecure 모드로 실행 (HTTP 허용)
    server.insecure: true

server:
  service:
    type: ClusterIP
    port: 80

  # ArgoCD test기본 제공 ingress 비활성화 (별도 생성)
  ingress:
    enabled: false

  # insecure 모드 활성화
  extraArgs:
    - --insecure

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true