replicaCount: 1

image:
  repository: 492021314651.dkr.ecr.us-west-2.amazonaws.com/youtube-reporter-app
  tag: build-123  # ✅ 이 값은 Jenkins가 빌드 번호에 따라 자동으로 바꿔줍니다
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
