apiVersion: v1
kind: Service
metadata:
  name: youtube-reporter
spec:
  type: {{ .Values.service.type }}
  selector:
    app: youtube-reporter
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000

